version: "3.8"

services:
  loki:
    image: grafana/loki:2.8.4
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - loki-data:/loki
      - ./loki-config.yaml:/etc/loki/loki-config.yaml

volumes:
  loki-data:
